name: Build, Push, and Run Cypress Tests

on:
  push:
    branches:
      - main # Run workflow on pushes to the `main` branch
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/cypress-project:latest .

    # Step 4: Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/cypress-project:latest

  run-tests:
    name: Pull and Run Cypress Tests
    runs-on: ubuntu-latest
    needs: build-and-push # Depends on the previous job

    steps:
    # Step 1: Pull the Docker image from Docker Hub
    - name: Pull Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/cypress-project:latest

    # Step 2: Run Cypress tests inside the container
    - name: Run Cypress tests
      run: |
        docker run --rm \
          -e CYPRESS_VALID_EMAIL=${{ secrets.CYPRESS_VALID_EMAIL }} \
          -e CYPRESS_VALID_PASSWORD=${{ secrets.CYPRESS_VALID_PASSWORD }} \
          ${{ secrets.DOCKER_USERNAME }}/cypress-project:latest
          
        
      